// <auto-generated />
namespace ScaffoldTest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Manolo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Manolo));
        
        string IMigrationMetadata.Id
        {
            get { return "201304221959383_Manolo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
